import random

print("This is a dice rolling stimulator")

leaveprogram = 0
while leaveprogram != "q":
    print("Press enter to roll")
    input()
    number = random.randint(1, 6)
    if number == 1:
        print("[----------]")
        print("[          ]")
        print("[     O    ]")
        print("[          ]")
        print("[----------]")
        print()
        print("Move Forward 1 step.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
    if number == 2:
        print("[----------]")
        print("[          ]")
        print("[ O      O ]")
        print("[          ]")
        print("[----------]")
        print()
        print("Move Forward 2 steps.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
    if number == 3:
        print("[----------]")
        print("[ O      O ]")
        print("[     O    ]")
        print("[          ]")
        print("[----------]")
        print()
        print("Move Forward 3 steps.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
    if number == 4:
        print("[----------]")
        print("[ O      O ]")
        print("[          ]")
        print("[ O      O ]")
        print("[----------]")
        print()
        print("Move Forward 4 steps.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
    if number == 5:
        print("[----------]")
        print("[ O      O ]")
        print("[     O    ]")
        print("[ O      O ]")
        print("[----------]")
        print()
        print("Move Forward 5 steps.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
    if number == 6:
        print("[----------]")
        print("[ O      O ]")
        print("[ O      O ]")
        print("[ O      O ]")
        print("[----------]")
        print()
        print("Move Forward 6 steps.")
        print()
        print("Enter 'q' to quit()")
        leaveprogram = input()
